/*
 * Blinky Demo - RTA-OS Style Task Demo
 * Target: AURIX TC4x (TriCore) on QEMU
 * 
 * Demonstrates RTA-OS compatible task definitions and API usage.
 * Based on ETAS RTA-OS 5.0.2 patterns.
 */

#include "osek.h"
#include "osek_types.h"
#include <stdint.h>

/*============================================================================
 * Task Declarations (RTA-OS Style)
 * In real RTA-OS, these are generated by the configurator
 *============================================================================*/

/* Forward declare the task structures */
DeclareTask(Task_Blink);
DeclareTask(Task_Monitor);

/* Resource declarations */
DeclareResource(Resource_LED);

/* Alarm declarations */
DeclareAlarm(Alarm_Blink);

/* Counter declarations */
DeclareCounter(Counter_System);

/*============================================================================
 * Task Configuration Data (RTA-OS Style)
 * In real RTA-OS, this is auto-generated in Os_Cfg.c
 *============================================================================*/

/* Task stacks */
static uint32_t Task_Blink_Stack[256];
static uint32_t Task_Monitor_Stack[256];

/* Static task descriptors */
static const struct Os_TaskType_s Task_Blink_Descriptor = {
    .index = 0,
    .name = "Task_Blink",
    .coreId = 0,
    .basePriority = 2,
    .imask = 0x8000U,
    .maxActivations = 1,
    .autostart = FALSE,
    .autostartModes = OSDEFAULTAPPMODE,
    .entryPoint = NULL,  /* Set during init */
    .stackBase = Task_Blink_Stack,
    .stackSize = sizeof(Task_Blink_Stack)
};

static const struct Os_TaskType_s Task_Monitor_Descriptor = {
    .index = 1,
    .name = "Task_Monitor",
    .coreId = 0,
    .basePriority = 1,
    .imask = 0x8000U,
    .maxActivations = 1,
    .autostart = TRUE,
    .autostartModes = OSDEFAULTAPPMODE,
    .entryPoint = NULL,  /* Set during init */
    .stackBase = Task_Monitor_Stack,
    .stackSize = sizeof(Task_Monitor_Stack)
};

/* TaskType pointers (what the API uses) */
CONSTP2CONST(Os_TaskType, OS_CONST, TYPEDEF) Task_Blink = &Task_Blink_Descriptor;
CONSTP2CONST(Os_TaskType, OS_CONST, TYPEDEF) Task_Monitor = &Task_Monitor_Descriptor;

/*============================================================================
 * Resource Configuration Data
 *============================================================================*/

static const struct Os_ResourceType_s Resource_LED_Descriptor = {
    .index = 0,
    .name = "Resource_LED",
    .ceilingPriority = 3,
    .coreId = 0
};

CONSTP2CONST(Os_ResourceType, OS_CONST, TYPEDEF) Resource_LED = &Resource_LED_Descriptor;

/*============================================================================
 * Counter and Alarm Configuration Data
 *============================================================================*/

static const struct Os_CounterType_s Counter_System_Descriptor = {
    .index = 0,
    .name = "Counter_System",
    .maxAllowedValue = 0xFFFFFFFFU,
    .ticksPerBase = 1,
    .minCycle = 1,
    .coreId = 0
};

CONSTP2CONST(Os_CounterType_Internal, OS_CONST, TYPEDEF) Counter_System = &Counter_System_Descriptor;

static const struct Os_AlarmType_s Alarm_Blink_Descriptor = {
    .index = 0,
    .name = "Alarm_Blink",
    .counter = NULL,  /* Set during init to Counter_System */
    .actionType = OS_ALARM_ACTION_ACTIVATETASK,
    .action.taskId = NULL  /* Set during init to Task_Blink */
};

CONSTP2CONST(Os_AlarmType, OS_CONST, TYPEDEF) Alarm_Blink = &Alarm_Blink_Descriptor;

/*============================================================================
 * LED State (simulated)
 *============================================================================*/

static volatile uint32_t led_state = 0;

/*============================================================================
 * Task Implementations (RTA-OS Style)
 * 
 * TASK(name) expands to: void Os_Entry_name(void)
 * TerminateTask() is just 'return' in RTA-OS!
 *============================================================================*/

/*
 * Blink task - toggles LED periodically
 * Entry function: Os_Entry_Task_Blink
 */
TASK(Task_Blink)
{
    /* Acquire LED resource */
    GetResource(Resource_LED);
    
    /* Toggle LED state (simulated - actual GPIO in target project) */
    led_state = !led_state;
    
    /* Release LED resource */
    ReleaseResource(Resource_LED);
    
    /* Terminate task - in RTA-OS this is just 'return' */
    TerminateTask();
    /* Note: TerminateTask() expands to 'return' so no code after it */
}

/*
 * Monitor task - checks system state
 * Entry function: Os_Entry_Task_Monitor
 */
TASK(Task_Monitor)
{
    static uint32_t counter = 0;
    
    counter++;
    
    /* Periodically activate blink task */
    if (counter % 5 == 0) {
        ActivateTask(Task_Blink);
    }
    
    /* Check LED state */
    if (counter >= 10) {
        /* After 10 activations, reset counter */
        counter = 0;
    }
    
    /* Terminate - just returns */
    TerminateTask();
}

/*============================================================================
 * ISR Implementations (RTA-OS Style)
 * ISR(name) expands to: void Os_Entry_name(void)
 *============================================================================*/

/*
 * System tick ISR - increments system counter
 */
ISR(ISR_SystemTick)
{
    /* Increment system counter */
    IncrementCounter(Counter_System);
}

/*============================================================================
 * Demo Initialization
 *============================================================================*/

void main_blinky(void)
{
    /* 
     * In real RTA-OS, all configuration is done by the ISOLAR-A tool
     * and generated into Os_Cfg.c / Os_Cfg.h.
     * 
     * For this demo, we just need to start the OS.
     * The task/resource/alarm definitions above simulate what
     * the configurator would generate.
     */
    
    /* Set the alarm to trigger Task_Blink every 100 ticks */
    SetRelAlarm(Alarm_Blink, 100, 100);
    
    /* Start the OS with default application mode */
    StartOS(OSDEFAULTAPPMODE);
    
    /* StartOS should not return, but if it does... */
    while (1) {
        /* Idle loop */
    }
}

/*============================================================================
 * OS Configuration Summary (RTA-OS Style)
 * 
 * Tasks:
 *   Task_Blink   - Priority 2, Core 0, Non-autostart
 *   Task_Monitor - Priority 1, Core 0, Autostart
 * 
 * Resources:
 *   Resource_LED - Ceiling priority 3
 * 
 * Counters:
 *   Counter_System - System tick counter
 * 
 * Alarms:
 *   Alarm_Blink - Activates Task_Blink periodically
 * 
 * API Usage Examples:
 *   ActivateTask(Task_Blink);       -> Os_ActivateTask(Task_Blink)
 *   GetResource(Resource_LED);      -> Os_GetResource(Resource_LED)
 *   ReleaseResource(Resource_LED);  -> Os_ReleaseResource(Resource_LED)
 *   TerminateTask();                -> return  (fast termination!)
 *   SetRelAlarm(Alarm_Blink, 100, 100);
 *   StartOS(OSDEFAULTAPPMODE);
 *============================================================================*/
